name: Generate APT Repository

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Aptly
        run: |
          sudo apt-get update && sudo apt-get install -y aptly
          aptly repo create -architectures=amd64 -component=main -distribution=stable microcks-cli-repo
          
      - name: Build Dummy Package
        run: |
          mkdir -p mock-pkg/DEBIAN
          echo -e "Package: microcks-cli\nVersion: 1.0.0\nArchitecture: amd64\nMaintainer: Me\nDescription: Test" > mock-pkg/DEBIAN/control
          dpkg-deb --build mock-pkg dist/microcks-cli_1.0.0_linux_amd64.deb
          aptly repo add -force-replace=true microcks-cli-repo dist/ 

      - name: Publish
        run: |
          mkdir -p public
          aptly publish repo -skip-signing=true -architectures=amd64 -force-overwrite=true microcks-cli-repo public
          echo "<h1>APT Repo Active</h1>" > public/index.html
          touch public/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy
        uses: actions/deploy-pages@v4
